### ISSUE TITLE
使用html5parse时报错了

### ISSUE THREAD

**Issue by Create-Peace** [acrazing/html5parser#1]
yarn add html5parse后，在html5parseTest.js中写以下代码：
` ``js
var html = require('html5parser')

const input = `
<!DOCTYPE html>
<html>
  <body>
    <h1 id="hello">Hello world</h1>
  </body>
</html>
`

const ast = html.parse(input)

html.walk(ast, {
  enter: (node) => {
    if (node.type === html.SyntaxKind.Tag) {
      for (const attr of node.attributes) {
        if (attr.value !== void 0) {
          // This is used for present the ranges of attributes.
          console.log(input.substring(attr.value.start, attr.value.end))
          // you can get the value directly:
          console.log(attr.value.value)
        }
      }
    }
  }
})
```
但是node html5parseTest.js
报错：
Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/apple/Desktop/workSpace/node_modules/html5parser/lib/index.js:12:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by acrazing** [comment]
yarn add tslib

**Comment by Create-Peace** [comment]
谢谢啦，解决了，能问一下，你的思路怎么样的？
